version: '3.9'

services:
  db:
    image: postgres:14
    volumes:
      - ./data/db:/var/lib/postgresql/data:Z
    privileged: true
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 itjobs.wsgi:application
    volumes:
      - .:/app:Z
    ports:
      - "8000:8000"
    privileged: true
    environment:
      - DJANGO_SETTINGS_MODULE=itjobs.settings.prod
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    entrypoint: /bin/sh -c "python manage.py migrate && python manage.py loaddata cities.json && gunicorn --bind 0.0.0.0:8000 itjobs.wsgi:application"

  nginx: 
    image: nginx:latest 
    ports: 
      - "80:80" 
    volumes: 
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:Z
      - ./itjobs/staticfiles:/app/staticfiles:Z
    depends_on: 
      - web 