apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.celery.name }}
  labels:
    app: {{ .Values.celery.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.celery.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.celery.name }}
    spec:
      containers:
       - name: {{ .Values.celery.name }}
          image: "{{ .Values.celery.image.repository }}:{{ .Values.celery.image.tag }}"
          command: ["celery", "-A", "itjobs", "worker", "--loglevel=info"]
          env:
            - name: REDIS_HOST
              value: redis
            - name: DJANGO_SETTINGS_MODULE
              value: itjobs.settings.prod

