apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itjobs-ingress
    
spec:
  rules:
    - http:
        paths:
          - path: {{ .Values.nginx.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginx.name }}
                port:
                  number: {{ .Values.nginx.service.port }}

