apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: itjobs-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: itjobs-https-redirect@kubernetescrd
    
spec:
  rules:
    - host: itjobs.os-fonder.ru
      http:
        paths:
          - path: {{ .Values.nginx.ingress.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.nginx.name }}
                port:
                  number: {{ .Values.nginx.service.port }}
  tls:
  - hosts:
    - itjobs.os-fonder.ru
    secretName: itjobs-tls