apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nginx.name }}
spec:
  type: {{ .Values.nginx.service.type }}
  ports:
    - port: {{ .Values.nginx.service.port }}
  selector:
    app: {{ .Values.nginx.name }}

