# Generated by Django 3.2.13 on 2022-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20220523_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='on_moderation',
            field=models.BooleanField(default=True),
        ),
    ]
