# Generated by Django 3.2.13 on 2022-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_tag_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
