# Generated by Django 3.2.13 on 2022-05-24 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_city_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='job',
            name='update_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
