# Generated by Django 3.2.13 on 2022-05-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_auto_20220524_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='company',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='job',
            name='contacts',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
