# Generated by Django 3.2.13 on 2022-05-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20220525_2040'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='net_salary_from',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='net_salary_to',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
