# Generated by Django 3.2.13 on 2022-05-28 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20220528_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='on_moderation',
        ),
        migrations.AddField(
            model_name='job',
            name='moderated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='web.city'),
        ),
    ]
