replicaCount: 1

web:
  name: web
  image:
    repository: famer/itjobs
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 8000

nginx:
  name: nginx
  image:
    repository: famer/itjobs-nginx
    tag: "latest"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    path: /

celery:
  name: celery
  image:
    repository: famer/itjobs
    tag: "latest"
    pullPolicy: IfNotPresent

db:
  name: db
  image:
    repository: postgres
    tag: "14"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 5432

redis:
  name: redis
  image:
    repository: redis
    tag: "alpine"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 6379
