name: Testing
on: push

jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unittests
      run: |
        pip3 install --user django
        pip3 install django-simple-captcha
        python3 manage.py test