name: CI/CD Pipeline

 on:
   push:
     branches:
       - main  # Change this to your deployment branch, e.g., master or production

 jobs:
   build:
     runs-on: ubuntu-latest

     steps:
     - name: Checkout code
       uses: actions/checkout@v3

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Log in to Docker Hub
       uses: docker/login-action@v2
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}

     - name: Build and Push Docker image
       run: |
         docker build -t famer/itjobs:latest .
         docker push famer/itjobs:latest
     - name: Deploy to Production Server
       env:
         SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
       run: |
         echo "${SSH_PRIVATE_KEY}" > key.pem
         chmod 600 key.pem
         ssh -p 2206 -o StrictHostKeyChecking=no -i key.pem core@gorbierd.ddns.net 'cd itjobs && docker pull famer/itjobs:latest && docker-compose down && docker-compose up -d'