name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your deployment branch, e.g., master or production

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        touch .env
        docker compose build
        docker compose push

    - name: Deploy to Production Server
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_HOST: ${{ secrets.SERVER_HOST }}
        SERVER_SSH_PORT: ${{ secrets.SERVER_SSH_PORT }}
        SERVER_USER: ${{ secrets.SERVER_USER }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > key.pem
        chmod 600 key.pem
        ssh -p $SERVER_SSH_PORT -o StrictHostKeyChecking=no -i key.pem $SERVER_USER@$SERVER_HOST 'cd itjobs &&  git fetch --all && git reset --hard origin/main && docker pull famer/itjobs:latest && docker-compose down && docker-compose up -d --build'